{{- if .Values.ingress.enabled }}
{{- $fullName := include "airflow.fullname" . }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "airflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ $fullName }}
              servicePort: 80
{{- end }}