---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort
  selector:
    app: {{ template "airflow.name" . }}-webserver
    release: {{ .Release.Name }}